sudo: required

language: generic

services:
- docker

arch:
  packages:
  - mpich
  - gcc
  - cpplint
  script:
  - ./test_all.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
