sudo: required

language: cpp

services:
- docker

arch:
  packages:
  - openmpi
  - cpplint
  script:
  - ./test_all.sh

# script:
#   - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
